apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${ARGOCD_AWS_ACCOUNT}:role/JenkinsRole"
    #eks.amazonaws.com/role-arn: "arn:aws:iam::350206045032:role/JenkinsRole"