apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: django-secrets # referenced to in deployment.yaml
  namespace: django
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: django-secrets # must match `SecretStore` name
    kind: SecretStore
  target:
    name: django-secrets
    creationPolicy: Owner # Owner # Owner managed by ESO # Merge
    immutable: true # check
  data:
    - secretKey: DB_USERNAME # arbitrary assigned key name, used in deployment.yaml
      remoteRef:
        key: rds_user  # The path to SSM parameter
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
    - secretKey: DB_NAME # arbitrary assigned key name, used in deployment.yaml
      remoteRef:
        key: rds_dbname  # The path to SSM parameter
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
    - secretKey: DB_PASSWORD # arbitrary assigned key name, used in deployment.yaml
      remoteRef:
        key: rds_password  # The path to SSM parameter
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
    - secretKey: DB_PORT # arbitrary assigned key name, used in deployment.yaml
      remoteRef:
        key: rds_port  # The path to SSM parameter
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
    - secretKey: DB_HOST # arbitrary assigned key name, used in deployment.yaml
      remoteRef:
        key: rds_endpoint  # The path to SSM parameter
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
    - secretKey: SECRET_KEY # arbitrary assigned key name, used in deployment.yaml
      remoteRef:
        key: django_secretkey  # The path to SSM parameter
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: django-secrets
  namespace: django
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1  # $AWS_REGION # AWS region specific, pending dynamic value
      auth:
        jwt: # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: django # name of actual serviceAccount (not role)

# DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
# STATIC_ROOT=/static
# DEBUG="True"